name: on_exit
description: hook on dart process exit
version: 1.0.0
homepage: https://github.com/rmw-dart/on_exit

environment:
  sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies: 
  try_catch: ^1.0.2 

